import {
  BookOpen,
  Briefcase,
  Camera,
  Clapperboard,
  Clock,
  Code,
  Coffee,
  Dumbbell,
  Film,
  Folder,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Landmark,
  Lightbulb,
  MapPin,
  Mic,
  Monitor,
  Music,
  Newspaper,
  Palette,
  PenTool,
  Plane,
  Rocket,
  Server,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Star,
  Terminal,
  Trophy,
  Tv,
  Users,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Categories and collections store a lucide icon *name* in the database;
 * this registry resolves it to a component and doubles as the option
 * list for the icon picker.
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  code: Code,
  "graduation-cap": GraduationCap,
  wallet: Wallet,
  "shopping-bag": ShoppingBag,
  clapperboard: Clapperboard,
  newspaper: Newspaper,
  zap: Zap,
  users: Users,
  briefcase: Briefcase,
  folder: Folder,
  clock: Clock,
  "book-open": BookOpen,
  palette: Palette,
  globe: Globe,
  heart: Heart,
  star: Star,
  music: Music,
  camera: Camera,
  gamepad: Gamepad2,
  plane: Plane,
  home: Home,
  coffee: Coffee,
  dumbbell: Dumbbell,
  film: Film,
  gift: Gift,
  lightbulb: Lightbulb,
  landmark: Landmark,
  "map-pin": MapPin,
  mic: Mic,
  monitor: Monitor,
  "pen-tool": PenTool,
  rocket: Rocket,
  server: Server,
  smartphone: Smartphone,
  terminal: Terminal,
  trophy: Trophy,
  tv: Tv,
  wrench: Wrench,
};

export const ICON_NAMES = Object.keys(ICON_MAP);

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Folder;
}

export const SWATCH_COLORS = [
  "#8B5CF6",
  "#6366F1",
  "#3B82F6",
  "#06B6D4",
  "#14B8A6",
  "#10B981",
  "#F59E0B",
  "#F97316",
  "#EF4444",
  "#EC4899",
  "#64748B",
];
